branch-defaults:
  master:
    environment: artanzels-env
global:
  application_name: artanzels
  default_ec2_keyname: artanzelkeypair
  default_platform: 64bit Amazon Linux 2015.09 v2.0.8 running Ruby 2.2 (Passenger
    Standalone)
  default_region: us-west-2
  profile: eb-cli
  sc: git
